# Spring Profile:
spring.profiles.active=prod

spring.config.import=optional:file:.env[.properties]

#Server port:
server.port=${PORT:8080}

#DataBase:
#spring.datasource.url=jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:chatDB}
#spring.datasource.username=${RDS_USERNAME:postgres}
#spring.datasource.password=${RDS_PASSWORD:postgres}
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${DB_URL}
spring.datasource.username=${RDS_USERNAME:postgres}
spring.datasource.password=${RDS_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

#Redis:
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:admin}

#Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

#Flyway:
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

#WebSocket config:
socket.dest-prefixes=/topic, /specific
socket.app-prefix=/app
socket.endpoint=/chat
socket.topic-prefix=/topic
socket.notify-prefix=/specific/notify
socket.error-prefix=/specific/error
socket.time-to-first-message=999999

#Security:
security.jwt.secret-key=${SECRET_KEY}
security.jwt.access-expiration=60m
# 7 days
security.jwt.refresh-expiration=10080m
security.jwt.email-expiration=120m

#CORS
cors.allowed-origins=${CORS_ORIGINS:http://localhost:8080,http://localhost:5557,http://localhost:3000,\
  http://85.235.140.66:8080/,http://10.11.0.100:3000}
cors.allowed-methods=GET, POST, PUT, PATCH, DELETE
cors.allowed-headers=*
cors.allow-credentials=true

# SMTP Configuration
spring.mail.username=${EMAIL_ADDRESS:FinalProjectLinkedin@gmail.com}
spring.mail.password=${EMAIL_PASSWORD:y j p d b u g n m t s d o p t i}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.protocols=TLSv1.2
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

#Logging:
logging.file.path=logs/chat.log

##Swagger
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.api-docs.path=/v3/api-docs
