#version: '3.8'
#
#services:
#  postgres_service:
#    container_name: postgres-chat-db
#    image: postgres:16.3
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_USER: postgres
#      POSTGRES_DB: chatDB
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#
#  master:
#    container_name: redis-chat-master
#    hostname: redis-chat
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    restart: always
#    volumes:
#      - /var/docker-volumes/redis-data:/data
#    command: redis-server --requirepass admin
#
#  redis-commander:
#    container_name: redis-commander
#    hostname: redis-commander
#    image: rediscommander/redis-commander:latest
#    restart: always
#    environment:
#      - REDIS_HOSTS=local:redis-chat:6379:0:admin
#    ports:
#      - "8081:8081"
#volumes:
#  postgres_data: